spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
    username: rm553791
    password: 180298
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
  server:
    address: 0.0.0.0  # Permite conexões externas
    port: 8080        # Porta que o Spring Boot escuta
